<!DOCTYPE html>
<html>
	<head>
		<link type="text/css" rel="stylesheet" href="stylesheet.css"/>
		<title></title>
	</head>
	<body>
	<div id="header">
	<h3>Christina Aguilera</h3>
	
	<a href="http://www.biography.com/people/christina-aguilera-9542394">Source</a>
	</div>
	<div class="left">
	  <table id="album">
	    <tr>
	      <td><img src="http://upload.wikimedia.org/wikipedia/commons/3/35/Christina_Aguilera_at_the_premiere_of_Burlesque_%282010%29.jpg"/></td>
	      <td><img src="http://static.idolator.com/uploads/2010/11/christina-aguilera-400x300.jpg"/></td>
	    </tr>
	    <tr>
	      <td><img src="http://cdn23.us3.fansshare.com/photos/christinaaguilera/christina-aguilera-ca-young-319142857.jpg"/></td>
	      <td><img src="http://2.bp.blogspot.com/-ZuUCKMaVXKU/UEEKOEHBqpI/AAAAAAAABxQ/i0goWj6AJrM/s1600/mzi.mhthhjtn.1200x1200-75.jpg"/></td>
	    </tr>
	    <tr>
	      <td><img src="http://www.christinaaguilera.com/sites/caguilera/files/imagecache/preview/christina_aguilera001.jpg"/></td>
	      <td><img src="http://cdn.stylisheve.com/wp-content/uploads/2012/05/Christina-Aguilera-Hairstyles-_04.jpg"/></td>
	    </tr>
	  </table>
	</div>
	<div class="right">
	   <div class="content">
			<h4>Personal Info</h4>
			<ul>
				<li>Name: Christina Aguilera</li>
				<li>Occupation: Singer, Songwriter</li>
				<li>Birth date: 18 Dec 1980</li>
				<li>Place of birth: Staten Island, NY</li>
			</ul>
			<h4>Introduction</h4>
			<p>American singer Christina Aguilera is best known for the single "Genie In A Bottle" and the controversial, sexually charged album Stripped.</p>
			<p>She was born on December 18, 1980 in Staten Island, New York. Aguilera began her career as a cast member on The All New Mickey Mouse Club. She rapidly rose to stardom following the release of her hit single, "Genie In A Bottle," which earned her a Grammy Award for best new artist. Her other hit singles include "What A Girl Wants," "Come on Over Baby," "Lady Marmalade" and the sexually charged "Dirrty." In recent years, Aguilera has served as a coach and mentor on the singing-competition show The Voice.</p>
		</div>	
	</div>
	
	<div id="footer"></div>
	</body>
</html>
